version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    image: dervinhdo/code-review-backend:v0.0.4
    container_name: code-review-backend
    depends_on:
      - postgres
    restart: always
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ENCRYPTION_SECRET: ${ENCRYPTION_SECRET}
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:8080"
  frontend:
    image: dervinhdo/code-review-frontend:v0.0.3
    container_name: code-review-frontend
    depends_on:
      - backend
    restart: always
    environment:
      VITE_BASE_PATH: http://localhost:8080
    ports:
      - "5173:80"

volumes:
  postgres_data: